name: My First Workflow
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  pull_request:
  workflow_dispatch:

jobs:
  my-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, windows-2022, macos-14 ]
        java: [8, 11, 17, 21, 25]
    runs-on: ${{ matrix.os }}
    steps:
      - shell: bash
        run: echo "I'm running on ${{ runner.os }}"
      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - shell: bash
        run: java -version
  print-a-string:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    env:
      MY_JOB_VAR: job
    outputs:
      dice_outcome: ${{ steps.dice.outputs.outcome }}
    steps:
      - name: Hello World
        id: step1
        run: echo Hello, World!
      - name: Throw a dice
        id: dice
        run: echo outcome=$(ruby -e 'puts rand(0..10)') >> "$GITHUB_OUTPUT"
      - name: Checkout the repo
        uses: actions/checkout@v5.0.1
        with:
          fetch-depth: '0'
          fetch-tags: 'true'
      - name: Print contextual information
        env:
          MY_STEP_VAR: step
        shell: bash
        run: |
          echo github.action = ${{ github.action }}
          echo github.actor = ${{ github.actor }}
          echo github.event = ${{ github.event }}
          echo github.event_name = ${{ github.event_name }}
          echo github.ref = ${{ github.ref }}
          echo github.repository = ${{ github.repository }}
          echo github.repository_id = ${{ github.repository_id }}
          echo github.action = ${{ github.repository_owner }}
          echo github.sha = ${{ github.sha }}
          echo github.token = ${{ github.token }}
          echo env.PATH = ${{ github.PATH }}
          echo env.MY_JOB_VAR = ${{ github.MY_JOB_VAR }}
          echo env.MY_STEP_VAR = ${{ github.MY_STEP_VAR }}
          echo steps.step1.outcome = ${{ steps.step1.outcome }}
          echo runner.os = ${{ runner.os }}
      - name: this one fails on pull requests
        if: github.event_name == 'pull_request'
        run: false
      - name: always run
        if: always()
        run: echo I always run
      - name: run on failures
        if: failure()
        run: echo Failure detected
      - name: Print Gradle Tasks
        shell: bash
        run: ./gradlew tasks

  run-on-windows:
    needs:
      - print-a-string
    runs-on: windows-2022
    steps:
      - name: Hello World
        run: echo Hello, World!
      - name: run a bash script
        shell: bash
        run: for i in {1..3}; do echo step $i; done
      - name: Print if the dice is higher than 5 (actual value is ${{ needs.print-a-string.outputs.dice_outcome }}
        if: needs.print-a-string.outputs.dice_outcome > 5
        run: echo Dice returned ${{ needs.print-a-string.outputs.dice_outcome }}
