name: My First Workflow
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  pull_request:
  workflow_dispatch:

jobs:
  print-a-string:
    runs-on: ubuntu-24.04
    steps:
      - name: Hello World
        run: echo Hello, World!
      - name: Checkout the repo
        uses: actions/checkout@v5.0.1
      - name: Print Gradle Tasks
        shell: bash
        run: ./gradlew tasks
      - name: this one fails
        run: false
      - name: always run
        if: always()
        run: echo I always run
      - name: run on failures
        if: failure()
        run: echo Failure detected
  run-on-windows:
    runs-on: windows-2022
    steps:
      - name: Hello World
        run: echo Hello, World!
      - name: run a bash script
        shell: bash
        run: for i in {1..3}; do echo step $i; done
