name: My First Workflow
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  pull_request:
  workflow_dispatch:

jobs:
  print-a-string:
    runs-on: ubuntu-24.04
    steps:
      - name: Hello World
        run: echo Hello, World!
      - name: Checkout the repo
        uses: actions/checkout@v5.0.1
      - name: Print Gradle Tasks
        run: ./gradlew tasks
